### ISSUE TITLE
FTP dirs look like files and GoCoEdit fails to open them

### ISSUE THREAD

**Issue by pioneerwebsites** [gogolith/gocoeditserver#12]
Been considering GoCoEdit but needed to view a file from an FTP server and so I purchased it.

I added the remote FTP server, connected successfully, and the dir list shows the dates in full format with only enough room for a few letters of the end of the dir name.

What's more, the dirs can't be entered. After tapping any dir, the app reports "Can't open file, no access" etc.

I set the initial dir to a specific dir and get a similar error message, "Can't open file".

I only have read access to some dirs, but have write access to one and it behaves the same. Device is iPad Pro 9.3.2.

**Comment by gogolith** [comment]
Hi,
thank you for the report. Sound like an issue with your ftp server. What type of ftp server is running on your server?

regards

Am 29.07.2016 um 09:28 schrieb Pioneer Websites <notifications@github.com<mailto:notifications@github.com>>:


Been considering GoCoEdit but needed to view a file from an FTP server and so I purchased it.

I added the remote FTP server, connected successfully, and the dir list shows the dates in full format with only enough room for a few letters of the end of the dir name.

What's more, the dirs can't be entered. After tapping any dir, the app reports "Can't open file, no access" etc.

I set the initial dir to a specific dir and get a similar error message, "Can't open file".

I only have read access to some dirs, but have write access to one and it behaves the same. Device is iPad Pro 9.3.2.

-

**Comment by pioneerwebsites** [comment]
Thanks for the quick reply, it helps with the disappointment... :-)

I don't manage this server, which is why I only have read permissions on some dirs.

I believe it is Windows OS but that's all I know.

It functions perfectly and quickly with my desktop FTP client (ie. FileZilla) and always has.

**Comment by HerbertLancaster** [comment]
I recently purchased the app and am haveing  the same issue connecting to a hosted ftp site. This ftp site is a GoDaddy ftp site that I have had for many years. Unfortunately I have very little information on the specific details of the actual FTP server. It is your typical big hosted site with very little control, all I can really do is create users, grant them file path  access and give them rw or ro access.

I can tell you that I have downloaded some other fairly generic ftp apps for my iPhone and they DO NOT have this problem. Of course, they are only single feature ftp client apps, nothing like GoCoEdit! 

I would really like to resolve this issue , because GoCoEdit is a VERY NICE  APP, and I really would like to be able to FTP directly to some live angular apps and be able to use the editors full potential!!

You can contact me directly if there is something I could try. Thank you in advance.

Cheers and nice APP!!!

**Comment by gogolith** [comment]
this sould be solved in the current version.
